on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: thxtomslf/matrix
    steps:
      - uses: actions/checkout@v3
      - run: make check

  memcheck:
    runs-on: ubuntu-latest
    container: thxtomslf/matrix
    steps:
      - uses: actions/checkout@v3
      - run: make memcheck

  build:
    runs-on: ubuntu-latest
    container: thxtomslf/matrix
    steps:
      - uses: actions/checkout@v3
      - run: make build

  test:
    runs-on: ubuntu-latest
    container: thxtomslf/matrix
    steps:
      - uses: actions/checkout@v3
      - run: make test